version: "3.5"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_HOST: localhost
      MYSQL_USER: natan
      MYSQL_PASSWORD: natan
    volumes:
      - mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql # nome do serviço MySQL
      PMA_PORT: 3306 # porta do MySQL
    ports:
      - "8080:80" # porta do phpMyAdmin
    depends_on:
      - mysql
    networks:
      - mysql

networks:
  mysql:
    driver: bridge

volumes:
  mysql: